remote_theme: wowthemesnet/mediumish-theme-jekyll

# Site
name: "Drishti Kalhans"
title: "Drishti Kalhans"
description: "My personal blogspace."
logo: '/img.png'
favicon: '/favico.png'
baseurl: /mediumish-theme-jekyll
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  drishti:
    name: Drishti Kalhans
    display_name: Drishti
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dk23drishti@gmail.com
    web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "Bachelors from Delhi University. Pursuing Masters in Political Science and International Relations."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
